-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "123" SALT 'b0d831b49ece4e1e' HASH 'bdc3e023fe828620892c905f1e5196577552e6dc3c766a19339d2ee02fbe4b1f' ADMIN;        
CREATE MEMORY TABLE "PUBLIC"."flyway_schema_history"(
    "installed_rank" INTEGER NOT NULL,
    "version" CHARACTER VARYING(50),
    "description" CHARACTER VARYING(200) NOT NULL,
    "type" CHARACTER VARYING(20) NOT NULL,
    "script" CHARACTER VARYING(1000) NOT NULL,
    "checksum" INTEGER,
    "installed_by" CHARACTER VARYING(100) NOT NULL,
    "installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "execution_time" INTEGER NOT NULL,
    "success" BOOLEAN NOT NULL
);               
ALTER TABLE "PUBLIC"."flyway_schema_history" ADD CONSTRAINT "PUBLIC"."flyway_schema_history_pk" PRIMARY KEY("installed_rank");
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.flyway_schema_history;   
INSERT INTO "PUBLIC"."flyway_schema_history" VALUES
(-1, NULL, '<< Flyway Schema History table created >>', 'TABLE', '', NULL, '123', TIMESTAMP '2025-02-07 22:00:15.938618', 0, TRUE);      
CREATE INDEX "PUBLIC"."flyway_schema_history_s_idx" ON "PUBLIC"."flyway_schema_history"("success" NULLS FIRST);               
CREATE MEMORY TABLE "PUBLIC"."MATCH"(
    "ID" UUID NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "MODIFIED_AT" TIMESTAMP(6)
);            
ALTER TABLE "PUBLIC"."MATCH" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MATCH;   
CREATE MEMORY TABLE "PUBLIC"."POOL"(
    "ID" UUID NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "MODIFIED_AT" TIMESTAMP(6),
    "ENTRY_PRICE" FLOAT(53),
    "FORMAT" ENUM('ELIMINATION', 'GROUP_ELIMINATION', 'LEAGUE'),
    "NAME" CHARACTER VARYING(255),
    "STATE" ENUM('FINISHED', 'IN_PROGRESS', 'OPEN'),
    "CREATOR_ID" UUID
);           
ALTER TABLE "PUBLIC"."POOL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POOL;    
CREATE MEMORY TABLE "PUBLIC"."POOL_TEAMS"(
    "POOL_ID" UUID NOT NULL,
    "TEAMS_ID" UUID NOT NULL
);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POOL_TEAMS;              
CREATE MEMORY TABLE "PUBLIC"."POOL_PARTICIPANT"(
    "ID" UUID NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "MODIFIED_AT" TIMESTAMP(6),
    "JOIN_DATE" TIMESTAMP(6),
    "PAID" BOOLEAN,
    "PAYMENT_DETAILS" ENUM('CARD', 'CASH', 'OTHER', 'TRANSFER'),
    "TOTAL_POINTS" BIGINT,
    "POOL_ID" UUID,
    "USER_ID" UUID
);     
ALTER TABLE "PUBLIC"."POOL_PARTICIPANT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_43" PRIMARY KEY("ID");            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POOL_PARTICIPANT;        
CREATE MEMORY TABLE "PUBLIC"."POOL_RESULT"(
    "ID" UUID NOT NULL,
    "COMPLETION_DATE" TIMESTAMP(6),
    "TOTAL_PRIZE" FLOAT(53),
    "POOL_ID" UUID,
    "WINNER_ID" UUID
);        
ALTER TABLE "PUBLIC"."POOL_RESULT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POOL_RESULT;             
CREATE MEMORY TABLE "PUBLIC"."TEAM"(
    "ID" UUID NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "MODIFIED_AT" TIMESTAMP(6),
    "NAME" CHARACTER VARYING(255),
    "PLAYERS" CHARACTER VARYING(255) ARRAY,
    "POOL_ID" UUID
);       
ALTER TABLE "PUBLIC"."TEAM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_27" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TEAM;    
CREATE MEMORY TABLE "PUBLIC"."USERS"(
    "ID" UUID NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "MODIFIED_AT" TIMESTAMP(6),
    "EMAIL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "SURNAME" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255)
);            
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."UK6DOTKOTT2KJSP8VW4D0M25FB7" UNIQUE NULLS DISTINCT ("EMAIL");           
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."UKR43AF9AP4EDM43MMTQ01ODDJ6" UNIQUE NULLS DISTINCT ("USERNAME");        
ALTER TABLE "PUBLIC"."POOL_TEAMS" ADD CONSTRAINT "PUBLIC"."UKG6AYMRVLHW62RBO96U0EHSJL7" UNIQUE NULLS DISTINCT ("TEAMS_ID");   
ALTER TABLE "PUBLIC"."TEAM" ADD CONSTRAINT "PUBLIC"."FKJA4JH56AL6U6LH5VA8PQ9I5QL" FOREIGN KEY("POOL_ID") REFERENCES "PUBLIC"."POOL"("ID") NOCHECK;            
ALTER TABLE "PUBLIC"."POOL_RESULT" ADD CONSTRAINT "PUBLIC"."FKCVXXJ5HBOV6UCYFA5IUKMP63H" FOREIGN KEY("POOL_ID") REFERENCES "PUBLIC"."POOL"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."POOL" ADD CONSTRAINT "PUBLIC"."FKHRAFU5BCEVJ3LJI5WNINVN19U" FOREIGN KEY("CREATOR_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."POOL_PARTICIPANT" ADD CONSTRAINT "PUBLIC"."FKESXTYIEV9Q7O7F5CLRSDVCGM8" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."POOL_RESULT" ADD CONSTRAINT "PUBLIC"."FKS4E3MTINQSKO6QC29194FJ531" FOREIGN KEY("WINNER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."POOL_TEAMS" ADD CONSTRAINT "PUBLIC"."FKN15R9SQOEQDKEOYCIKTJOXFGD" FOREIGN KEY("TEAMS_ID") REFERENCES "PUBLIC"."TEAM"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."POOL_PARTICIPANT" ADD CONSTRAINT "PUBLIC"."FKOF9J8XPN4FJ6M80E8WUM66K4N" FOREIGN KEY("POOL_ID") REFERENCES "PUBLIC"."POOL"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."POOL_TEAMS" ADD CONSTRAINT "PUBLIC"."FKOSYSMG9565UOMV9N9JPMJTCN6" FOREIGN KEY("POOL_ID") REFERENCES "PUBLIC"."POOL"("ID") NOCHECK;      
